version: "3.9"

services:
  # =========================
  # AUTH SERVICE DB
  # =========================
  auth-db:
    image: postgres:16
    container_name: auth_service_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data

  # =========================
  # PRODUCT SERVICE DB
  # =========================
  product-db:
    image: postgres:16
    container_name: product_service_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: product_db
    ports:
      - "5433:5432"
    volumes:
      - product_db_data:/var/lib/postgresql/data

  # =========================
  # INVENTORY SERVICE DB
  # =========================
  inventory-db:
    image: postgres:16
    container_name: inventory_service_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: inventory_db
    ports:
      - "5434:5432"
    volumes:
      - inventory_db_data:/var/lib/postgresql/data

  # =========================
  # ORDER SERVICE DB
  # =========================
  order-db:
    image: postgres:16
    container_name: order_service_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: order_db
    ports:
      - "5435:5432"
    volumes:
      - order_db_data:/var/lib/postgresql/data

  # =========================
  # STORE SERVICE DB
  # =========================
  store-db:
    image: postgres:16
    container_name: store_service_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: store_db
    ports:
      - "5436:5432"
    volumes:
      - store_db_data:/var/lib/postgresql/data

  # =========================
  # STORE SERVICE DB
  # =========================

  payment-db:
    image: postgres:16
    container_name: payment_service_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment_db
    ports:
      - "5437:5432"
    volumes:
      - payment_db_data:/var/lib/postgresql/data

  # =========================
  # RABBITMQ 4 + MANAGEMENT
  # =========================
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   # AMQP
      - "15672:15672" # Management UI
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  seq:
    image: datalust/seq:latest
    container_name: bukidlink-seq
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SEQ_PASSWORD: "password"
    ports:
      - "5341:5341"
      - "8080:80"
    volumes:
      - seq-data:/data

# =========================
# VOLUMES
# =========================
volumes:
  product_db_data:
  inventory_db_data:
  order_db_data:
  auth_db_data:
  store_db_data:
  payment_db_data:
  rabbitmq_data:
  seq-data:
