using ProductCatalogAPI.Domain;

namespace ProductCatalogAPI.Features.ProductVariants.GetProductVariantsByIds;

public record GetProductVariantByIdsResult(IEnumerable<ProductVariant> ProductVariants);